### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by skabbit** [KamitaniLab/icnn#3]
Hello, KamitaniLab!
Really interested in your research and trying to reproduce some of the results, but no luck. I've build and installed caffe deepsim branch (on Ubuntu 18.04, tried both CPU and GPU).

After running your examples I've got only `recon_img_from_decoded_feature_icnn_dgn_gd.py` working, at least it converges to some image (but suspiciously fast, just after 10th iteration it is almost not changing, just become more dark).

All other examples has issues and result is not something expected:
1. All "true_feature" examples gives a black image. Also on running throw a warning:
```
recon_img_from_true_feature_icnn_dgn_gd.py:97: RuntimeWarning: divide by zero encountered in divide
  weights = 1. / (feat_norm_list**2)
recon_img_from_true_feature_icnn_dgn_gd.py:100: RuntimeWarning: invalid value encountered in divide
  weights = weights / weights.sum()
```
Checked, feat_norm_list all are zeros. And it's not a problem of PIL, it works well.

2. Both L-BGFS reconstruction of decoded features gives no iteration and empty result, here is the log:
```
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =         4096     M =           10
 The initial X is infeasible.  Restart with its projection.

At X0      2058 variables are exactly at the bounds

At iterate    0    f=  1.27654D+05    |proj g|=  0.00000D+00

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
 4096      0      1      0     0     0   0.000D+00   1.277D+05
  F =   127653.96191406250     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            

 Cauchy                time 0.000E+00 seconds.
 Subspace minimization time 0.000E+00 seconds.
 Line search           time 0.000E+00 seconds.

 Total User time 0.000E+00 seconds.
```

What's possible problem do I have?
Is there any solution or advice to resolve this?

**Comment by skabbit** [comment]
Running `recon_img_from_decoded_feature_icnn_gd.py` gives strange static err.
```
iter=1; err=127654;
iter=2; err=127654;
iter=3; err=127654;
iter=4; err=127654;
iter=5; err=127654;
iter=6; err=127654;
iter=7; err=127654;
iter=8; err=127654;
iter=9; err=127654;
iter=10; err=127654;
iter=11; err=127654;
iter=12; err=127654;
iter=13; err=127654;
iter=14; err=127654;
iter=15; err=127654;
iter=16; err=127654;
iter=17; err=127654;
...
```

Result image is whole orange square.

**Comment by skabbit** [comment]
I've made a Google Colab notebook to run examples with GPU support and reproduce my results entirely.
(Original caffe deepsim branch have some bugs and need Makefile.config be updated for Colab compatibility, so I use my own repo for that.)

Here is link to notebook: [https://colab.research.google.com/drive/1fvrI-TW0TWpaB9vgzgW-McViQtC0n38O?usp=sharing](https://colab.research.google.com/drive/1fvrI-TW0TWpaB9vgzgW-McViQtC0n38O?usp=sharing)

**Comment by skabbit** [comment]
Does cuDNN is needed to run it?

**Comment by skabbit** [comment]
Possibly, I found the reason.
`/.downloadnet.sh vgg19` downloads HTML, not model file, with content like:
`<p>The document has moved <a href="https://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_19_layers.caffemodel">here</a>.</p>`

I fixed it in pull request: https://github.com/KamitaniLab/icnn/pull/2

**Comment by ShuntaroAoki** [comment]
Thank you so much for the fix!
Seems working perfectly and I've merged your PR.
Sorry for late response.

BTW, your colab-compatible deepsim caffe-fr-chairs is REALLY helpful.
Great job!

**Comment by skabbit** [comment]
@ShuntaroAoki thank you for your response! I'm glad to know my work helps you!

Also, I'm trying to reconstruct your pipeline of raw fMRI preprocessing. Does you have publish code for that anywhere?
Thank you in advance.

**Comment by ShuntaroAoki** [comment]
>Does you have publish code for that anywhere?

Not yet since the original preprocessing code relies on our obsoleted in-house data structure and a bit time-consuming (and less demand) to adapt for public. However, it's off course desirable to release all analysis code including preprocessing pipeline and we would like to release it in future.

Alternatively, we recently use fmriprep for preprocessing in our lab and found that data preprocessed by it successfully replicate the original reconstruction.

**Comment by skabbit** [comment]
Thanks again for answer!
I'm working with fmriprep lib as well and just started to replicate pipeline described at Shen, Horikawa, Majima, and Kamitani (2019) "Deep image reconstruction from human brain activity". I want to use results of this research (or more [recent](https://www.frontiersin.org/articles/10.3389/fncom.2019.00021/full)) in my current artistic project. I'll appreciate code you could share, and if you need I could help you with publishing that. 
Thanks in advance.
